package com.boob.greendog.mapper;

import com.boob.greendog.model.Medicine;
import com.boob.greendog.model.MedicineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MedicineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    long countByExample(MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int deleteByExample(MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int insert(Medicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int insertSelective(Medicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    List<Medicine> selectByExampleWithRowbounds(MedicineExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    List<Medicine> selectByExample(MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    Medicine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") Medicine record, @Param("example") MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int updateByExample(@Param("record") Medicine record, @Param("example") MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int updateByPrimaryKeySelective(Medicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int updateByPrimaryKey(Medicine record);
}