package com.boob.greendog.mapper;

import com.boob.greendog.model.Packet;
import com.boob.greendog.model.PacketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PacketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    long countByExample(PacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int deleteByExample(PacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int insert(Packet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int insertSelective(Packet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    List<Packet> selectByExampleWithRowbounds(PacketExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    List<Packet> selectByExample(PacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    Packet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") Packet record, @Param("example") PacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int updateByExample(@Param("record") Packet record, @Param("example") PacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int updateByPrimaryKeySelective(Packet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packet
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    int updateByPrimaryKey(Packet record);
}