server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/greendog?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pawn2589
  devtools:
    restart:
      enabled: true  #设置开启热部署
  thymeleaf:
    cache: false #关闭默认模板引擎缓存
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB #配置最大文件上传
      max-request-size: 100MB #配置最大请求

#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml