package com.boob.greendog.model;

import java.util.Date;

public class Administrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.id
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.name
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.nickname
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.account
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.password
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.id
     *
     * @return the value of administrator.id
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.id
     *
     * @param id the value for administrator.id
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.name
     *
     * @return the value of administrator.name
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.name
     *
     * @param name the value for administrator.name
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.nickname
     *
     * @return the value of administrator.nickname
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.nickname
     *
     * @param nickname the value for administrator.nickname
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.account
     *
     * @return the value of administrator.account
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.account
     *
     * @param account the value for administrator.account
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.password
     *
     * @return the value of administrator.password
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.password
     *
     * @param password the value for administrator.password
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.gmt_created
     *
     * @return the value of administrator.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.gmt_created
     *
     * @param gmtCreated the value for administrator.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.gmt_modified
     *
     * @return the value of administrator.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.gmt_modified
     *
     * @param gmtModified the value for administrator.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:55 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}