package com.boob.greendog.model;

import java.util.Date;

public class Apply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.id
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.customer_id
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.pet_id
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    private Long petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.type
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.handle
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    private Integer handle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.reply
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    private Integer reply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.gmt_created
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.gmt_modified
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.id
     *
     * @return the value of apply.id
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.id
     *
     * @param id the value for apply.id
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.customer_id
     *
     * @return the value of apply.customer_id
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.customer_id
     *
     * @param customerId the value for apply.customer_id
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.pet_id
     *
     * @return the value of apply.pet_id
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public Long getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.pet_id
     *
     * @param petId the value for apply.pet_id
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.type
     *
     * @return the value of apply.type
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.type
     *
     * @param type the value for apply.type
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.handle
     *
     * @return the value of apply.handle
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public Integer getHandle() {
        return handle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.handle
     *
     * @param handle the value for apply.handle
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public void setHandle(Integer handle) {
        this.handle = handle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.reply
     *
     * @return the value of apply.reply
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public Integer getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.reply
     *
     * @param reply the value for apply.reply
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public void setReply(Integer reply) {
        this.reply = reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.gmt_created
     *
     * @return the value of apply.gmt_created
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.gmt_created
     *
     * @param gmtCreated the value for apply.gmt_created
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.gmt_modified
     *
     * @return the value of apply.gmt_modified
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.gmt_modified
     *
     * @param gmtModified the value for apply.gmt_modified
     *
     * @mbg.generated Thu Mar 12 15:46:41 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}