package com.boob.greendog.model;

import java.util.Date;

public class Appointment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.pet_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.doctor_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.disease_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long diseaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.handle
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Integer handle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.reply
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Integer reply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Float price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.id
     *
     * @return the value of appointment.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.id
     *
     * @param id the value for appointment.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.pet_id
     *
     * @return the value of appointment.pet_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.pet_id
     *
     * @param petId the value for appointment.pet_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.doctor_id
     *
     * @return the value of appointment.doctor_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.doctor_id
     *
     * @param doctorId the value for appointment.doctor_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.disease_id
     *
     * @return the value of appointment.disease_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.disease_id
     *
     * @param diseaseId the value for appointment.disease_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setDiseaseId(Long diseaseId) {
        this.diseaseId = diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.handle
     *
     * @return the value of appointment.handle
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Integer getHandle() {
        return handle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.handle
     *
     * @param handle the value for appointment.handle
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setHandle(Integer handle) {
        this.handle = handle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.reply
     *
     * @return the value of appointment.reply
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Integer getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.reply
     *
     * @param reply the value for appointment.reply
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setReply(Integer reply) {
        this.reply = reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.gmt_created
     *
     * @return the value of appointment.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.gmt_created
     *
     * @param gmtCreated the value for appointment.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.gmt_modified
     *
     * @return the value of appointment.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.gmt_modified
     *
     * @param gmtModified the value for appointment.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.customer_id
     *
     * @return the value of appointment.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.customer_id
     *
     * @param customerId the value for appointment.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.price
     *
     * @return the value of appointment.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.price
     *
     * @param price the value for appointment.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setPrice(Float price) {
        this.price = price;
    }
}