package com.boob.greendog.model;

import java.util.Date;

public class Bill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.goods_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.type
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.count
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Float price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id
     *
     * @return the value of bill.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id
     *
     * @param id the value for bill.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.goods_id
     *
     * @return the value of bill.goods_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.goods_id
     *
     * @param goodsId the value for bill.goods_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.type
     *
     * @return the value of bill.type
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.type
     *
     * @param type the value for bill.type
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.gmt_created
     *
     * @return the value of bill.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.gmt_created
     *
     * @param gmtCreated the value for bill.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.gmt_modified
     *
     * @return the value of bill.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.gmt_modified
     *
     * @param gmtModified the value for bill.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.customer_id
     *
     * @return the value of bill.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.customer_id
     *
     * @param customerId the value for bill.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.count
     *
     * @return the value of bill.count
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.count
     *
     * @param count the value for bill.count
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.price
     *
     * @return the value of bill.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.price
     *
     * @param price the value for bill.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setPrice(Float price) {
        this.price = price;
    }
}