package com.boob.greendog.model;

import java.util.Date;

public class Disease {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.name
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.description
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.id
     *
     * @return the value of disease.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.id
     *
     * @param id the value for disease.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.name
     *
     * @return the value of disease.name
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.name
     *
     * @param name the value for disease.name
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.description
     *
     * @return the value of disease.description
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.description
     *
     * @param description the value for disease.description
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.price
     *
     * @return the value of disease.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.price
     *
     * @param price the value for disease.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.gmt_created
     *
     * @return the value of disease.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.gmt_created
     *
     * @param gmtCreated the value for disease.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.gmt_modified
     *
     * @return the value of disease.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.gmt_modified
     *
     * @param gmtModified the value for disease.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}