package com.boob.greendog.model;

import java.util.Date;

public class Instance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.pet_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.doctor_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.disease_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long diseaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.id
     *
     * @return the value of instance.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.id
     *
     * @param id the value for instance.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.pet_id
     *
     * @return the value of instance.pet_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.pet_id
     *
     * @param petId the value for instance.pet_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.doctor_id
     *
     * @return the value of instance.doctor_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.doctor_id
     *
     * @param doctorId the value for instance.doctor_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.disease_id
     *
     * @return the value of instance.disease_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.disease_id
     *
     * @param diseaseId the value for instance.disease_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setDiseaseId(Long diseaseId) {
        this.diseaseId = diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.gmt_created
     *
     * @return the value of instance.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.gmt_created
     *
     * @param gmtCreated the value for instance.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.gmt_modified
     *
     * @return the value of instance.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.gmt_modified
     *
     * @param gmtModified the value for instance.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.customer_id
     *
     * @return the value of instance.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.customer_id
     *
     * @param customerId the value for instance.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
}