package com.boob.greendog.model;

import java.util.Date;

public class Medicine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.name
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.description
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.pic
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.status
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.id
     *
     * @return the value of medicine.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.id
     *
     * @param id the value for medicine.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.name
     *
     * @return the value of medicine.name
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.name
     *
     * @param name the value for medicine.name
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.description
     *
     * @return the value of medicine.description
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.description
     *
     * @param description the value for medicine.description
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.pic
     *
     * @return the value of medicine.pic
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.pic
     *
     * @param pic the value for medicine.pic
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.price
     *
     * @return the value of medicine.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.price
     *
     * @param price the value for medicine.price
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.gmt_created
     *
     * @return the value of medicine.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.gmt_created
     *
     * @param gmtCreated the value for medicine.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.gmt_modified
     *
     * @return the value of medicine.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.gmt_modified
     *
     * @param gmtModified the value for medicine.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.status
     *
     * @return the value of medicine.status
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.status
     *
     * @param status the value for medicine.status
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}