package com.boob.greendog.model;

import java.util.Date;

public class Packet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet.total_money
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Float totalMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet.shop_money
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Float shopMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet.surplus_money
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Float surplusMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column packet.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet.id
     *
     * @return the value of packet.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet.id
     *
     * @param id the value for packet.id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet.customer_id
     *
     * @return the value of packet.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet.customer_id
     *
     * @param customerId the value for packet.customer_id
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet.total_money
     *
     * @return the value of packet.total_money
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Float getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet.total_money
     *
     * @param totalMoney the value for packet.total_money
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setTotalMoney(Float totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet.shop_money
     *
     * @return the value of packet.shop_money
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Float getShopMoney() {
        return shopMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet.shop_money
     *
     * @param shopMoney the value for packet.shop_money
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setShopMoney(Float shopMoney) {
        this.shopMoney = shopMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet.surplus_money
     *
     * @return the value of packet.surplus_money
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Float getSurplusMoney() {
        return surplusMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet.surplus_money
     *
     * @param surplusMoney the value for packet.surplus_money
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setSurplusMoney(Float surplusMoney) {
        this.surplusMoney = surplusMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet.gmt_created
     *
     * @return the value of packet.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet.gmt_created
     *
     * @param gmtCreated the value for packet.gmt_created
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column packet.gmt_modified
     *
     * @return the value of packet.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column packet.gmt_modified
     *
     * @param gmtModified the value for packet.gmt_modified
     *
     * @mbg.generated Sat Mar 21 21:55:56 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}