package com.boob.greendog.model;

import java.util.Date;

public class Staff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.id
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.customer_id
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.name
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.sex
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.age
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.pic
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.address
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.contact
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.gmt_created
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.gmt_modified
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.id
     *
     * @return the value of staff.id
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.id
     *
     * @param id the value for staff.id
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.customer_id
     *
     * @return the value of staff.customer_id
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.customer_id
     *
     * @param customerId the value for staff.customer_id
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.name
     *
     * @return the value of staff.name
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.name
     *
     * @param name the value for staff.name
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.sex
     *
     * @return the value of staff.sex
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.sex
     *
     * @param sex the value for staff.sex
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.age
     *
     * @return the value of staff.age
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.age
     *
     * @param age the value for staff.age
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.pic
     *
     * @return the value of staff.pic
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.pic
     *
     * @param pic the value for staff.pic
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.address
     *
     * @return the value of staff.address
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.address
     *
     * @param address the value for staff.address
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.contact
     *
     * @return the value of staff.contact
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.contact
     *
     * @param contact the value for staff.contact
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.gmt_created
     *
     * @return the value of staff.gmt_created
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.gmt_created
     *
     * @param gmtCreated the value for staff.gmt_created
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.gmt_modified
     *
     * @return the value of staff.gmt_modified
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.gmt_modified
     *
     * @param gmtModified the value for staff.gmt_modified
     *
     * @mbg.generated Sun Mar 15 18:09:53 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}